version: "3.5"
services:
    app_php:
        build:
            context: ./bin/php
            dockerfile: Dockerfile
        container_name: app_php
        working_dir: /var/www/html/app
        networks:
            - app
        volumes:
            - ./api:/var/www/html/app
    webserver_nginx:
        build: 
            context: ./bin/nginx
            dockerfile: Dockerfile
        container_name: webserver
        working_dir: /var/www/html/app
        networks:
            - app
        ports:
            - "8081:80"
        volumes:
            - ./api:/var/www/html/app
            - ./bin/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
networks:
    app:
        driver: bridge
        